### ISSUE TITLE
Improve plot

### ISSUE THREAD

**Issue by sverhoeven** [classmodel/class-web#74]
Continuation of #30

- [x] Plot vertical profiles
- [x] Add axes
- [x] Nicer axis extents/ticks
- [x] Render all permutations of experiment
- [x] Render more than one experiment
- [x] Add legend
- [x] Add color cycling
- [ ] Tooltip on hover 
  - [x] Simply use SVG title element. But only works if mouse is exactly over path.
  - [ ] Continuation in https://github.com/classmodel/class-web/issues/82
- [x] Styling/font similar to SolidUI/Charts
  - [x] Tinkered with font family/size/weight/letter spacing etc now mostly similar
  - [x] For now stick with fixed axes and no grid lines as in chart.js, but open for opions.
- [x] Axis labels
- [ ] Make it possible to select variable https://github.com/classmodel/class-web/issues/84
- [ ] Make it possible to select time (playback controls?) https://github.com/classmodel/class-web/issues/85
- [x] Reuse own component in favour of solidui/chart for timeseries as well
  - [x] ~This makes the app much slower; can we optimize?~ Seems ok now
  - [x] Reduce history interval to 10 minutes instead of 1 minute; somewhat better but still not great
  - [x] Remove dead code / unneeded dependencies (chart.js, chart component)
  - [x] Fix playwright test: if we stick with this, the canvas is gone, so we cannot screenshot it
- [x] Make reactive (if data changes, update plot)
- [ ] Responsive width/height https://github.com/classmodel/class-web/issues/83
- [x] Verify that `gammaq`/`gammatheta` always available
- [ ] Add skew-T/log-p plots #75 
- [x] Move buttons to card header
- [ ] What should be the default height? (currently simply extending profiles by 400m)
- [ ] Do we want to modify units, e.g. from kg/kg to g/kg for more readable digits? Or time in hours/minuts rather than seconds?
- [x] Make typecheck happy
